### ISSUE TITLE
-Background parameter doesn't do much

### ISSUE THREAD

**Issue by PorreKaj** [psDevUK/UDSignature#1]
No matter what one throws at the Background parameter, it doesn't stick.

`New-UDSignature -Id "SignatureControl" -height 300 -width 800 -penColor Black -background 'rgba(255,0,0,0)'
`

For shits and giggles I tried to change the default value in the module as well.

Thanks.

**Comment by psDevUK** [comment]
Thanks for bringing this to my attention. I didn’t do much testing other than verifying it drew something on the dashboard. I haven’t forgot about mug request making that happy again

**Comment by psDevUK** [comment]
Yep that's me having a dinlow moment, and not entering backgroundColor fixed it now, will upload 2nd version to Github presently.
