### ISSUE TITLE
Get-UDElement Support

### ISSUE THREAD

**Issue by adamdriscoll** [psDevUK/UDSignature#2]
To implement Get-UDElement support you need to use the global UniversalDashboard object to listen for requests for state. 

Here is how the checkbox does it. The requestState message is what is called when you call Get-UDElement. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard.Materialize/Components/ud-checkbox.jsx#L23

**Comment by AlonGvili** [comment]
Loop critical

**Comment by AlonGvili** [comment]
Loop critical

**Comment by psDevUK** [comment]
Thanks for advice. Will look into implementing get-udelement support into this component

**Comment by psDevUK** [comment]
still struggling...if still struggling tomorrow, might have to do a thundercat call-out. Thanks

**Comment by psDevUK** [comment]
Boom finally got round to re-looking into this component, I can now save this as a base64 string image, and rerad the base64 string back, and covert this back to an image. Will update this repo with new version
